"""Create initial page and scrape tables

Revision ID: 3399810933e2
Revises: 
Create Date: 2021-07-04 09:12:02.800222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3399810933e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_id', sa.Integer(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('scrape_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_id', sa.Integer(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_extracted_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_id', sa.Integer(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_extracted_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_id', sa.Integer(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_extracted_page')
    op.drop_table('scrape_extracted_menu')
    op.drop_table('page')
    op.drop_table('file')
    op.drop_table('scrape')
    # ### end Alembic commands ###
